version: "3.9"

services:
  arkhamdb:
    container_name: arkhamdb
    env_file: devcontainer.env
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        PHP_VERSION: 7
        NODE_VERSION: lts/*
        COMPOSER_VERSION: 1
        CARD_DATA_PATH: /arkhamdb-json-data/
    depends_on:
      - database
    ports:
      - "8080:80"
    volumes:
      - ..:/var/www/html
      - ./000-default.conf:/etc/apache2/sites-enabled/000-default.conf

  database:
    image: mysql
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: arkhamdb
      MYSQL_USER: arkhamdb
      MYSQL_PASSWORD: arkhamdb
    ports:
      - "9906:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: